FROM golang:1.22-alpine

RUN apk add --no-cache git curl

RUN go install github.com/air-verse/air@v1.52.3

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080
CMD ["air", "-c", ".air.toml"]
